import React, { useEffect, useRef, useState } from 'react';
import {
  GraduationCap, ArrowRight, Sparkles, Brain, FileText,
  BarChart2, MessageSquare, Target, CheckCircle, Zap,
  ChevronDown, Star, Award
} from 'lucide-react';

interface LandingPageProps {
  onGetStarted: () => void;
}

const FEATURES = [
  {
    icon: Brain,
    color: 'from-indigo-500 to-purple-600',
    bg: 'bg-indigo-50',
    title: 'AI-Powered Questions',
    desc: 'Dynamic questions generated by Gemini AI, tailored to your target role, company, and resume sections — not generic templates.'
  },
  {
    icon: FileText,
    color: 'from-emerald-500 to-teal-600',
    bg: 'bg-emerald-50',
    title: 'Resume Intelligence',
    desc: 'Upload your PDF/DOCX and our LLM parser extracts your skills, projects, and experience to create hyper-personalized interview rounds.'
  },
  {
    icon: BarChart2,
    color: 'from-orange-500 to-red-500',
    bg: 'bg-orange-50',
    title: 'ATS Score Analysis',
    desc: 'Get your resume ATS score before the interview. See exactly how well it matches the job description and get improvement tips.'
  },
  {
    icon: MessageSquare,
    color: 'from-brand-500 to-indigo-600',
    bg: 'bg-brand-50',
    title: '6 Interview Rounds',
    desc: 'Behavioral, Technical, Situational, Resume Deep Dive, System Design, and more — covering every dimension of modern interviews.'
  },
  {
    icon: Target,
    color: 'from-pink-500 to-rose-600',
    bg: 'bg-pink-50',
    title: 'Company-Specific Prep',
    desc: 'Select Google, Meta, Amazon, Microsoft or any company. Questions reflect their actual hiring bar and culture expectations.'
  },
  {
    icon: Award,
    color: 'from-yellow-500 to-amber-600',
    bg: 'bg-yellow-50',
    title: 'Detailed Final Report',
    desc: 'Receive a comprehensive scorecard with per-round analysis, strengths, improvement areas, and curated study resources.'
  }
];

const STEPS = [
  { step: '01', title: 'Set Your Target', desc: 'Enter your name, target role (e.g. SWE) and company (e.g. Google). We calibrate the difficulty accordingly.' },
  { step: '02', title: 'Upload Your Resume', desc: 'Upload your PDF or DOCX resume. Our AI parser reads every section to craft personalized follow-up questions.' },
  { step: '03', title: 'Check ATS Score', desc: 'See how well your resume matches the target role before you start. Get instant improvement suggestions.' },
  { step: '04', title: 'Run the Interview', desc: 'Answer 6 rounds of AI-generated questions at your own pace. Type your responses naturally.' },
  { step: '05', title: 'Review Your Report', desc: 'Get a full scorecard with strengths, gaps, per-round scores, and curated resources to improve.' },
];

const STATS = [
  { value: '6', label: 'Interview Rounds', icon: Target },
  { value: '30+', label: 'Questions per Session', icon: MessageSquare },
  { value: '100%', label: 'AI Personalized', icon: Sparkles },
  { value: '∞', label: 'Practice Attempts', icon: Zap },
];

const ROLES = ['Software Engineer', 'Frontend Developer', 'Data Scientist', 'Product Manager', 'DevOps Engineer', 'Backend Developer', 'Data Analyst', 'Fullstack Developer'];
const COMPANIES = ['Google', 'Meta', 'Amazon', 'Microsoft', 'Netflix', 'TCS', 'Infosys', 'Startup'];

export const LandingPage: React.FC<LandingPageProps> = ({ onGetStarted }) => {
  const heroRef = useRef<HTMLDivElement>(null);
  const [roleIdx, setRoleIdx] = useState(0);
  const [companyIdx, setCompanyIdx] = useState(0);
  const [fadeRole, setFadeRole] = useState(true);
  const [fadeCompany, setFadeCompany] = useState(true);

  // Cycle through roles
  useEffect(() => {
    const t = setInterval(() => {
      setFadeRole(false);
      setTimeout(() => {
        setRoleIdx(i => (i + 1) % ROLES.length);
        setFadeRole(true);
      }, 300);
    }, 2000);
    return () => clearInterval(t);
  }, []);

  // Cycle through companies (offset)
  useEffect(() => {
    const t = setInterval(() => {
      setFadeCompany(false);
      setTimeout(() => {
        setCompanyIdx(i => (i + 1) % COMPANIES.length);
        setFadeCompany(true);
      }, 300);
    }, 2500);
    return () => clearInterval(t);
  }, []);

  const scrollToFeatures = () => {
    document.getElementById('features')?.scrollIntoView({ behavior: 'smooth' });
  };

  return (
    <div className="min-h-screen bg-white text-slate-800 overflow-x-hidden">

      {/* ── NAVBAR ── */}
      <header className="border-b border-slate-100 bg-white/80 backdrop-blur-md sticky top-0 z-50">
        <div className="max-w-6xl mx-auto px-4 py-4 flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <div className="bg-gradient-to-tr from-brand-600 to-indigo-500 p-2 rounded-xl text-white shadow-lg shadow-brand-500/20">
              <GraduationCap size={22} />
            </div>
            <div>
              <span className="font-extrabold text-xl tracking-tight text-slate-900">
                PrepMate <span className="text-brand-500">AI</span>
              </span>
              <p className="text-[10px] text-slate-400 font-semibold tracking-wider uppercase">Interview Sandbox</p>
            </div>
          </div>
          <button
            onClick={onGetStarted}
            className="bg-gradient-to-r from-brand-600 to-indigo-600 text-white text-sm font-bold px-5 py-2.5 rounded-xl hover:opacity-90 transition-all shadow-md shadow-brand-500/20 hover:shadow-lg hover:shadow-brand-500/30 hover:scale-[1.02] active:scale-95"
          >
            Start Free →
          </button>
        </div>
      </header>

      {/* ── HERO ── */}
      <section ref={heroRef} className="relative bg-gradient-to-b from-slate-50 via-indigo-50/30 to-white overflow-hidden">
        {/* Background blobs */}
        <div className="absolute top-0 left-1/4 w-96 h-96 bg-brand-500/10 rounded-full blur-3xl pointer-events-none" />
        <div className="absolute top-20 right-1/4 w-72 h-72 bg-purple-500/10 rounded-full blur-3xl pointer-events-none" />
        <div className="absolute bottom-0 left-0 w-64 h-64 bg-indigo-500/10 rounded-full blur-3xl pointer-events-none" />

        <div className="max-w-5xl mx-auto px-4 pt-24 pb-20 text-center relative z-10">
          {/* Badge */}
          <div className="inline-flex items-center gap-2 bg-brand-50 border border-brand-100 text-brand-600 text-xs font-bold px-4 py-2 rounded-full mb-8 animate-fade-in">
            <Sparkles size={12} />
            Powered by Gemini AI · Fully Personalized
          </div>

          {/* Headline */}
          <h1 className="text-5xl md:text-6xl font-extrabold tracking-tight text-slate-900 leading-tight mb-6 animate-slide-up">
            Ace Your Interview at{' '}
            <span
              className="bg-gradient-to-r from-brand-600 via-indigo-600 to-purple-600 bg-clip-text text-transparent transition-opacity duration-300"
              style={{ opacity: fadeCompany ? 1 : 0 }}
            >
              {COMPANIES[companyIdx]}
            </span>
            <br />
            as a{' '}
            <span
              className="bg-gradient-to-r from-emerald-500 to-teal-600 bg-clip-text text-transparent transition-opacity duration-300"
              style={{ opacity: fadeRole ? 1 : 0 }}
            >
              {ROLES[roleIdx]}
            </span>
          </h1>

          <p className="text-lg md:text-xl text-slate-500 max-w-2xl mx-auto mb-10 leading-relaxed animate-slide-up">
            Upload your resume. Set your target role and company. Get a hyper-personalized AI mock interview
            with <strong className="text-slate-700">6 rounds</strong>, ATS scoring, and a detailed performance report — all in minutes.
          </p>

          {/* CTAs */}
          <div className="flex flex-col sm:flex-row gap-4 justify-center items-center animate-slide-up">
            <button
              onClick={onGetStarted}
              id="hero-start-btn"
              className="bg-gradient-to-r from-brand-600 to-indigo-600 text-white font-bold text-base px-8 py-4 rounded-2xl shadow-xl shadow-brand-500/25 hover:shadow-2xl hover:shadow-brand-500/35 hover:scale-[1.03] active:scale-95 transition-all flex items-center gap-2"
            >
              <Zap size={18} />
              Start Mock Interview — Free
              <ArrowRight size={18} />
            </button>
            <button
              onClick={scrollToFeatures}
              className="text-slate-500 font-semibold text-sm flex items-center gap-2 hover:text-brand-500 transition-colors"
            >
              See how it works <ChevronDown size={16} />
            </button>
          </div>

          {/* Social proof */}
          <div className="mt-10 flex items-center justify-center gap-6 text-xs text-slate-400 font-semibold">
            <span className="flex items-center gap-1.5"><CheckCircle size={13} className="text-emerald-500" /> No signup required</span>
            <span className="flex items-center gap-1.5"><CheckCircle size={13} className="text-emerald-500" /> Resume stays private</span>
            <span className="flex items-center gap-1.5"><CheckCircle size={13} className="text-emerald-500" /> 100% AI-generated questions</span>
          </div>
        </div>

        {/* Mock UI preview card */}
        <div className="max-w-3xl mx-auto px-4 pb-16 relative z-10">
          <div className="bg-white rounded-2xl border border-slate-200 shadow-2xl shadow-slate-200/80 overflow-hidden">
            {/* Window chrome */}
            <div className="bg-slate-100 px-4 py-3 flex items-center gap-2 border-b border-slate-200">
              <div className="w-3 h-3 rounded-full bg-red-400" />
              <div className="w-3 h-3 rounded-full bg-yellow-400" />
              <div className="w-3 h-3 rounded-full bg-emerald-400" />
              <div className="flex-1 bg-white rounded-md px-3 py-1 text-xs text-slate-400 text-center font-mono ml-2">
                prepmate-ai.onrender.com
              </div>
            </div>
            {/* Mock interview UI */}
            <div className="p-6 bg-gradient-to-br from-slate-50 to-indigo-50/20">
              <div className="flex items-center gap-3 mb-4">
                <div className="w-8 h-8 bg-gradient-to-tr from-brand-600 to-indigo-500 rounded-lg flex items-center justify-center">
                  <Brain size={16} className="text-white" />
                </div>
                <div>
                  <p className="text-xs font-bold text-slate-800">Round 2 · Technical</p>
                  <p className="text-[10px] text-slate-400">Software Engineer @ Google · Question 2 of 5</p>
                </div>
                <div className="ml-auto bg-emerald-50 border border-emerald-100 text-emerald-700 text-[10px] font-bold px-2.5 py-1 rounded-full">
                  In Progress
                </div>
              </div>
              <div className="bg-white rounded-xl p-4 border border-slate-100 mb-4">
                <p className="text-sm text-slate-700 font-medium leading-relaxed">
                  💡 Explain the difference between a process and a thread in the context of your Node.js experience shown on your resume. How would you handle CPU-intensive tasks without blocking the event loop?
                </p>
              </div>
              <div className="bg-white rounded-xl p-3 border border-brand-100 border-dashed">
                <p className="text-xs text-slate-400 italic">Your answer appears here as you type...</p>
                <div className="mt-2 h-1.5 bg-slate-100 rounded-full overflow-hidden">
                  <div className="h-full w-3/5 bg-gradient-to-r from-brand-500 to-indigo-500 rounded-full animate-pulse" />
                </div>
              </div>
              {/* Score pills */}
              <div className="flex gap-2 mt-4">
                {['Technical ✦ 88', 'Communication ✦ 92', 'Depth ✦ 85'].map(s => (
                  <div key={s} className="bg-brand-50 text-brand-600 text-[10px] font-bold px-2.5 py-1 rounded-full border border-brand-100">
                    {s}
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ── STATS ── */}
      <section className="border-y border-slate-100 bg-white py-12">
        <div className="max-w-4xl mx-auto px-4 grid grid-cols-2 md:grid-cols-4 gap-8">
          {STATS.map(({ value, label, icon: Icon }) => (
            <div key={label} className="text-center">
              <div className="inline-flex items-center justify-center w-10 h-10 bg-brand-50 rounded-xl mb-3">
                <Icon size={18} className="text-brand-500" />
              </div>
              <p className="text-3xl font-extrabold text-slate-900 tracking-tight">{value}</p>
              <p className="text-xs text-slate-400 font-semibold mt-1">{label}</p>
            </div>
          ))}
        </div>
      </section>

      {/* ── FEATURES ── */}
      <section id="features" className="py-24 bg-gradient-to-b from-white to-slate-50">
        <div className="max-w-6xl mx-auto px-4">
          <div className="text-center mb-16">
            <p className="text-brand-500 text-xs font-bold tracking-widest uppercase mb-3">What You Get</p>
            <h2 className="text-4xl font-extrabold text-slate-900 tracking-tight">
              Everything you need to prepare smarter
            </h2>
            <p className="text-slate-500 mt-3 max-w-xl mx-auto">
              No generic question banks. Every question is generated fresh for your exact role, company, and resume.
            </p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {FEATURES.map(({ icon: Icon, color, title, desc }) => (
              <div
                key={title}
                className="bg-white border border-slate-100 rounded-2xl p-6 hover:shadow-xl hover:shadow-slate-200/60 hover:-translate-y-1 transition-all duration-300 group"
              >
                <div className={`inline-flex items-center justify-center w-12 h-12 rounded-xl bg-gradient-to-br ${color} mb-4 shadow-lg group-hover:scale-110 transition-transform`}>
                  <Icon size={22} className="text-white" />
                </div>
                <h3 className="font-bold text-slate-900 text-base mb-2">{title}</h3>
                <p className="text-sm text-slate-500 leading-relaxed">{desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── HOW IT WORKS ── */}
      <section id="how-it-works" className="py-24 bg-slate-50">
        <div className="max-w-4xl mx-auto px-4">
          <div className="text-center mb-16">
            <p className="text-brand-500 text-xs font-bold tracking-widest uppercase mb-3">The Process</p>
            <h2 className="text-4xl font-extrabold text-slate-900 tracking-tight">
              How PrepMate AI works
            </h2>
            <p className="text-slate-500 mt-3">From zero to a full interview report in under 10 minutes.</p>
          </div>
          <div className="relative">
            {/* Vertical line */}
            <div className="absolute left-8 top-0 bottom-0 w-px bg-gradient-to-b from-brand-200 via-indigo-200 to-transparent hidden md:block" />
            <div className="space-y-8">
              {STEPS.map(({ step, title, desc }) => (
                <div key={step} className="flex gap-6 items-start group">
                  <div className="flex-shrink-0 w-16 h-16 bg-gradient-to-br from-brand-500 to-indigo-600 rounded-2xl flex items-center justify-center text-white font-extrabold text-lg shadow-lg shadow-brand-500/20 group-hover:scale-105 transition-transform z-10">
                    {step}
                  </div>
                  <div className="bg-white rounded-2xl border border-slate-100 p-5 flex-1 hover:shadow-md hover:border-brand-100 transition-all">
                    <h3 className="font-bold text-slate-900 text-base mb-1">{title}</h3>
                    <p className="text-sm text-slate-500 leading-relaxed">{desc}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* ── INTERVIEW ROUNDS ── */}
      <section className="py-24 bg-white">
        <div className="max-w-5xl mx-auto px-4">
          <div className="text-center mb-16">
            <p className="text-brand-500 text-xs font-bold tracking-widest uppercase mb-3">Interview Structure</p>
            <h2 className="text-4xl font-extrabold text-slate-900 tracking-tight">6 Rounds. Full Coverage.</h2>
            <p className="text-slate-500 mt-3 max-w-xl mx-auto">
              Each round is independently scored and covers a different dimension of what interviewers actually test.
            </p>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {[
              { num: '01', name: 'Behavioral', desc: 'STAR-method answers for culture fit and soft skills', emoji: '🤝' },
              { num: '02', name: 'Technical', desc: 'Core CS concepts, language-specific depth, architecture', emoji: '⚙️' },
              { num: '03', name: 'Situational', desc: 'Real workplace scenarios — how you think and decide', emoji: '🧠' },
              { num: '04', name: 'Resume Deep Dive', desc: 'Your projects, experience, and achievements under scrutiny', emoji: '📄' },
              { num: '05', name: 'System Design', desc: 'Scalability, trade-offs, and architectural thinking', emoji: '🏗️' },
              { num: '06', name: 'Culture Fit', desc: 'Alignment with company values and team dynamics', emoji: '🌟' },
            ].map(({ num, name, desc, emoji }) => (
              <div
                key={num}
                className="border border-slate-100 rounded-2xl p-5 hover:border-brand-200 hover:bg-brand-50/30 hover:shadow-md transition-all group cursor-default"
              >
                <div className="flex items-center gap-3 mb-3">
                  <span className="text-2xl">{emoji}</span>
                  <div>
                    <p className="text-[10px] text-slate-400 font-bold uppercase tracking-wider">Round {num}</p>
                    <p className="font-bold text-slate-800 text-sm">{name}</p>
                  </div>
                </div>
                <p className="text-xs text-slate-500 leading-relaxed">{desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── CTA BANNER ── */}
      <section className="py-20 bg-gradient-to-br from-brand-600 via-indigo-600 to-purple-700 relative overflow-hidden">
        <div className="absolute inset-0 bg-[url('data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNjAiIGhlaWdodD0iNjAiIHZpZXdCb3g9IjAgMCA2MCA2MCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48ZyBmaWxsPSJub25lIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiPjxnIGZpbGw9IiNmZmZmZmYiIGZpbGwtb3BhY2l0eT0iMC4wNCI+PHBhdGggZD0iTTM2IDM0di00aC0ydjRoLTR2Mmg0djRoMnYtNGg0di0yaC00em0wLTMwVjBoLTJ2NGgtNHYyaDR2NGgyVjZoNFY0aC00ek02IDM0di00SDR2NEgwdjJoNHY0aDJ2LTRoNHYtMkg2ek02IDRWMEg0djRIMHYyaDR2NGgyVjZoNFY0SDZ6Ii8+PC9nPjwvZz48L3N2Zz4=')] opacity-30" />
        <div className="max-w-3xl mx-auto px-4 text-center relative z-10">
          <div className="inline-flex items-center gap-2 bg-white/20 text-white text-xs font-bold px-4 py-2 rounded-full mb-6">
            <Star size={12} className="fill-white" /> Completely free to use
          </div>
          <h2 className="text-4xl md:text-5xl font-extrabold text-white tracking-tight mb-4">
            Ready to land that offer?
          </h2>
          <p className="text-indigo-200 text-lg mb-10 max-w-xl mx-auto">
            Stop guessing what interviewers want. Practice with AI that knows your resume, your role, and your target company.
          </p>
          <button
            onClick={onGetStarted}
            id="cta-start-btn"
            className="bg-white text-brand-600 font-extrabold text-base px-10 py-4 rounded-2xl hover:bg-indigo-50 transition-all shadow-2xl hover:scale-[1.03] active:scale-95 flex items-center gap-2 mx-auto"
          >
            <Zap size={18} />
            Start Your Mock Interview Now
            <ArrowRight size={18} />
          </button>
          <p className="text-indigo-300 text-xs mt-4">No account needed · No credit card · Just practice</p>
        </div>
      </section>

      {/* ── FOOTER ── */}
      <footer className="border-t border-slate-100 bg-white py-8 text-center text-xs text-slate-400">
        <div className="flex items-center justify-center gap-2 mb-2">
          <div className="bg-gradient-to-tr from-brand-600 to-indigo-500 p-1.5 rounded-lg text-white">
            <GraduationCap size={14} />
          </div>
          <span className="font-bold text-slate-600">PrepMate AI</span>
        </div>
        <p>© 2026 PrepMate AI · Built with React + Node.js + Gemini · Mock Interview Sandbox</p>
        <p className="mt-1 text-slate-300">All interview data stays in your session. No data stored permanently.</p>
      </footer>
    </div>
  );
};
